apiVersion: v2
appVersion: 0.0.1
name: shoot-controller
description: Kubernetes controller to deploy the shoot agent
home: https://github.com/giantswarm/shoot-controller
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
sources:
  - https://github.com/giantswarm/shoot-controller
  - https://github.com/giantswarm/shoot
version: 0.5.0
keywords:
  - ai
  - troubleshooting
  - debugging
maintainers:
  - name: Giant Swarm
    email: team-phoenix@giantswarm.io
annotations:
  application.giantswarm.io/team: team-phoenix
