apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" . }}-openai
  namespace: {{ include "resource.default.namespace" . }}
  labels:
  {{- include "labels.common" . | nindent 4 }}
type: Opaque
data:
  openaiAPIKey: {{ .Values.openaiAPIKey | b64enc | quote }}
